#! /usr/bin/bash
#
# this is an "executable" which should run the compiler 
# '{self.cc} {options} {source_file}'
# Inputs: /path/to/program.c
# Outputs: /path/to/program (executable)

# Use last argument as filepath.
filepath=${!#}
# Strip the extension
base="${filepath%.*}"
# echo "Compiling $base (.c)"

# Preprocess
gcc -E -P $base.c -o $base.i

# if --lex or --parse, do not generate .s
CLASSPATH=/mnt/c/Users/dplas/dev/adventofcompilers/bin:/mnt/c/Users/dplas/dev/adventofcompilers/lib/guava-33.0.0-jre.jar
if [[ $1 == '--lex' || $1 == '--parse' || $1 == '--prettyprint' || $1 == '--codegen' || $1 == '--tacky' || $1 == '--validate' ]]; then
	java -classpath $CLASSPATH com.plasstech.lang.c.driver.Driver -- $1 < $base.i
else
	java -classpath $CLASSPATH com.plasstech.lang.c.driver.Driver < $base.i > $base.s
	rv=$?
	if [[ $rv == '0' ]]; then
		if [[ $1 == '-c' ]]; then
			gcc -c $base.s -o $base.o
		else
			gcc $base.s -o $base
		fi
	fi
	if [[ $1 != '-S' ]]; then 
		rm -f $base.s
	fi
	exit $rv
fi
